version: '3'

services:
  mongo:
    image: mongo 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=db
    ports: 
      - 27017:27017
    volumes:
      - ${PWD}/db_data:/data/db:Z

  api:
    image: josephmakin/logging-api
    environment:
      - FLASK_MONGO_URI=mongodb://admin:password@mongo/db?authSource=admin
    ports:
      - 5000:5000
